using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Telerik.WinControls.UI.Localization;

namespace GaikovBSUIR
{
    public class MyRuRadGridLocalizationProvider : Telerik.WinControls.UI.Localization.RadGridLocalizationProvider
    {

        public override string GetLocalizedString(string id)
        {
            switch (id)
            {
                case RadGridStringId.ConditionalFormattingPleaseSelectValidCellValue: return "Пожалуйста, выберите правильное значение ячейки";
                case RadGridStringId.ConditionalFormattingPleaseSetValidCellValue: return "Пожалуйста, установите действительные значение ячейки";
                case RadGridStringId.ConditionalFormattingPleaseSetValidCellValues: return "Пожалуйста, установите действительные значения ячеек";
                case RadGridStringId.ConditionalFormattingPleaseSetValidExpression: return "Пожалуйста, установите допустимое выражение";
                case RadGridStringId.ConditionalFormattingItem: return "Пункт";
                case RadGridStringId.ConditionalFormattingInvalidParameters: return "Недопустимые параметры";
                case RadGridStringId.FilterFunctionBetween: return "Между";
                case RadGridStringId.FilterFunctionContains: return "Содержит";
                case RadGridStringId.FilterFunctionDoesNotContain: return "Не содержит";
                case RadGridStringId.FilterFunctionEndsWith: return "Заканчивается";
                case RadGridStringId.FilterFunctionEqualTo: return "Равно";
                case RadGridStringId.FilterFunctionGreaterThan: return "Больше чем";
                case RadGridStringId.FilterFunctionGreaterThanOrEqualTo: return "Больше или равно";
                case RadGridStringId.FilterFunctionIsEmpty: return "Пусто";
                case RadGridStringId.FilterFunctionIsNull: return "Нулевой";
                case RadGridStringId.FilterFunctionLessThan: return "Меньше, чем";
                case RadGridStringId.FilterFunctionLessThanOrEqualTo: return "Меньше или равно";
                case RadGridStringId.FilterFunctionNoFilter: return "Нет фильтра";
                case RadGridStringId.FilterFunctionNotBetween: return "Не между";
                case RadGridStringId.FilterFunctionNotEqualTo: return "Не равно";
                case RadGridStringId.FilterFunctionNotIsEmpty: return "Не пусто";
                case RadGridStringId.FilterFunctionNotIsNull: return "Не нулевой";
                case RadGridStringId.FilterFunctionStartsWith: return "Начинается с";
                case RadGridStringId.FilterFunctionCustom: return "изготовленный на заказ";
                case RadGridStringId.FilterOperatorBetween: return "Между";
                case RadGridStringId.FilterOperatorContains: return "Содержит";
                case RadGridStringId.FilterOperatorDoesNotContain: return "Не содержит";
                case RadGridStringId.FilterOperatorEndsWith: return "EndsWith";
                case RadGridStringId.FilterOperatorEqualTo: return "Равно";
                case RadGridStringId.FilterOperatorGreaterThan: return "Больше чем";
                case RadGridStringId.FilterOperatorGreaterThanOrEqualTo: return "Более или равно";
                case RadGridStringId.FilterOperatorIsEmpty: return "Пусто";
                case RadGridStringId.FilterOperatorIsNull: return "Нулевой";
                case RadGridStringId.FilterOperatorLessThan: return "Меньше, чем";
                case RadGridStringId.FilterOperatorLessThanOrEqualTo: return "Меньше или равно";
                case RadGridStringId.FilterOperatorNoFilter: return "Нет фильтра";
                case RadGridStringId.FilterOperatorNotBetween: return "Не между";
                case RadGridStringId.FilterOperatorNotEqualTo: return "Не Равно";
                case RadGridStringId.FilterOperatorNotIsEmpty: return "Не пусто";
                case RadGridStringId.FilterOperatorNotIsNull: return "Не ноль";
                case RadGridStringId.FilterOperatorStartsWith: return "Начинается с";
                case RadGridStringId.FilterOperatorIsLike: return "подобно";
                case RadGridStringId.FilterOperatorNotIsLike: return "Не как";
                case RadGridStringId.FilterOperatorIsContainedIn: return "Содержалась в";
                case RadGridStringId.FilterOperatorNotIsContainedIn: return "Не Содержится в";
                case RadGridStringId.FilterOperatorCustom: return "Custom";
                case RadGridStringId.CustomFilterMenuItem: return "Custom";
                case RadGridStringId.CustomFilterDialogCaption: return "RadGridView Filter Dialog [{0}]";
                case RadGridStringId.CustomFilterDialogLabel: return "Show rows where:";
                case RadGridStringId.CustomFilterDialogRbAnd: return "And";
                case RadGridStringId.CustomFilterDialogRbOr: return "Or";
                case RadGridStringId.CustomFilterDialogBtnOk: return "OK";
                case RadGridStringId.CustomFilterDialogBtnCancel: return "Отмена";
                case RadGridStringId.CustomFilterDialogCheckBoxNot: return "Not";
                case RadGridStringId.CustomFilterDialogTrue: return "Правильно";
                case RadGridStringId.CustomFilterDialogFalse: return "Не правильно";
                case RadGridStringId.FilterMenuBlanks: return "Пустой";
                case RadGridStringId.FilterMenuAvailableFilters: return "Доступные фильтры";
                case RadGridStringId.FilterMenuSearchBoxText: return "Поиск...";
                case RadGridStringId.FilterMenuClearFilters: return "Очистить фильтр";
                case RadGridStringId.FilterMenuButtonOK: return "OK";
                case RadGridStringId.FilterMenuButtonCancel: return "Отмена";
                case RadGridStringId.FilterMenuSelectionAll: return "Все";
                case RadGridStringId.FilterMenuSelectionAllSearched: return "Все Результаты поиска";
                case RadGridStringId.FilterMenuSelectionNull: return "Ноль";
                case RadGridStringId.FilterMenuSelectionNotNull: return "Не ноль";
                case RadGridStringId.FilterFunctionSelectedDates: return "Фильтр по конкретным датам:";
                case RadGridStringId.FilterFunctionToday: return "Сегодня";
                case RadGridStringId.FilterFunctionYesterday: return "Вчера";
                case RadGridStringId.FilterFunctionDuringLast7days: return "В течение последних 7 дней";
                case RadGridStringId.FilterLogicalOperatorAnd: return "и";
                case RadGridStringId.FilterLogicalOperatorOr: return "или";
                case RadGridStringId.FilterCompositeNotOperator: return "НЕ";
                case RadGridStringId.DeleteRowMenuItem: return "Удалить строку";
                case RadGridStringId.SortAscendingMenuItem: return "Сортировать по возрастанию";
                case RadGridStringId.SortDescendingMenuItem: return "Сортировка по убыванию";
                case RadGridStringId.ClearSortingMenuItem: return "Очистить сортировка";
                case RadGridStringId.ConditionalFormattingMenuItem: return "Условное форматирование";
                case RadGridStringId.GroupByThisColumnMenuItem: return "Группировка по этой колонке";
                case RadGridStringId.UngroupThisColumn: return "В группе этой колонке";
                case RadGridStringId.ColumnChooserMenuItem: return "Выбрать колонку";
                case RadGridStringId.HideMenuItem: return "Скрыть колонку";
                case RadGridStringId.HideGroupMenuItem: return "Скрыть группы";
                case RadGridStringId.UnpinMenuItem: return "Открепить колонку";
                case RadGridStringId.UnpinRowMenuItem: return "Открепить ряд";
                case RadGridStringId.PinMenuItem: return "Закрепленные состояние";
                case RadGridStringId.PinAtLeftMenuItem: return "Закрепить слева";
                case RadGridStringId.PinAtRightMenuItem: return "Закрепить справа";
                case RadGridStringId.PinAtBottomMenuItem: return "Закрепить снизу";
                case RadGridStringId.PinAtTopMenuItem: return "Закрепить в верхней";
                case RadGridStringId.BestFitMenuItem: return "Наиболее подходящий";
                case RadGridStringId.PasteMenuItem: return "Вставить";
                case RadGridStringId.EditMenuItem: return "Редактировать";
                case RadGridStringId.ClearValueMenuItem: return "Очистить значение";
                case RadGridStringId.CopyMenuItem: return "Копировать";
                case RadGridStringId.CutMenuItem: return "Вырезать";
                case RadGridStringId.AddNewRowString: return "Нажмите чтобы добавить новую строку";
                case RadGridStringId.SearchRowResultsOfLabel: return "из";
                case RadGridStringId.SearchRowMatchCase: return "Учитывать регистр";
                case RadGridStringId.ConditionalFormattingSortAlphabetically: return "Сортировка столбцов по алфавиту";
                case RadGridStringId.ConditionalFormattingCaption: return "Условное форматирование Диспетчер правил";
                case RadGridStringId.ConditionalFormattingLblColumn: return "Формат только клетки с";
                case RadGridStringId.ConditionalFormattingLblName: return "Имя правила";
                case RadGridStringId.ConditionalFormattingLblType: return "Значение ячейки";
                case RadGridStringId.ConditionalFormattingLblValue1: return "Значение 1";
                case RadGridStringId.ConditionalFormattingLblValue2: return "Значение 2";
                case RadGridStringId.ConditionalFormattingGrpConditions: return "Правило";
                case RadGridStringId.ConditionalFormattingGrpProperties: return "Свойства правила";
                case RadGridStringId.ConditionalFormattingChkApplyToRow: return "Применить это форматирование ко всей строке";
                case RadGridStringId.ConditionalFormattingChkApplyOnSelectedRows: return "Применить это форматирование, если выбрана строка";
                case RadGridStringId.ConditionalFormattingBtnAdd: return "Добавить новое правило";
                case RadGridStringId.ConditionalFormattingBtnRemove: return "Удалить";
                case RadGridStringId.ConditionalFormattingBtnOK: return "OK";
                case RadGridStringId.ConditionalFormattingBtnCancel: return "Отмена";
                case RadGridStringId.ConditionalFormattingBtnApply: return "Apply";
                case RadGridStringId.ConditionalFormattingRuleAppliesOn: return "Rule applies to";
                case RadGridStringId.ConditionalFormattingCondition: return "Condition";
                case RadGridStringId.ConditionalFormattingExpression: return "Expression";
                case RadGridStringId.ConditionalFormattingChooseOne: return "[Choose one]";
                case RadGridStringId.ConditionalFormattingEqualsTo: return "equals to [Value1]";
                case RadGridStringId.ConditionalFormattingIsNotEqualTo: return "is not equal to [Value1]";
                case RadGridStringId.ConditionalFormattingStartsWith: return "starts with [Value1]";
                case RadGridStringId.ConditionalFormattingEndsWith: return "ends with [Value1]";
                case RadGridStringId.ConditionalFormattingContains: return "contains [Value1]";
                case RadGridStringId.ConditionalFormattingDoesNotContain: return "does not contain [Value1]";
                case RadGridStringId.ConditionalFormattingIsGreaterThan: return "is greater than [Value1]";
                case RadGridStringId.ConditionalFormattingIsGreaterThanOrEqual: return "is greater than or equal [Value1]";
                case RadGridStringId.ConditionalFormattingIsLessThan: return "is less than [Value1]";
                case RadGridStringId.ConditionalFormattingIsLessThanOrEqual: return "is less than or equal to [Value1]";
                case RadGridStringId.ConditionalFormattingIsBetween: return "is between [Value1] and [Value2]";
                case RadGridStringId.ConditionalFormattingIsNotBetween: return "is not between [Value1] and [Value1]";
                case RadGridStringId.ConditionalFormattingLblFormat: return "Format";
                case RadGridStringId.ConditionalFormattingBtnExpression: return "Expression editor";
                case RadGridStringId.ConditionalFormattingTextBoxExpression: return "Expression";
                case RadGridStringId.ConditionalFormattingPropertyGridCaseSensitive: return "CaseSensitive";
                case RadGridStringId.ConditionalFormattingPropertyGridCellBackColor: return "CellBackColor";
                case RadGridStringId.ConditionalFormattingPropertyGridCellForeColor: return "CellForeColor";
                case RadGridStringId.ConditionalFormattingPropertyGridEnabled: return "Enabled";
                case RadGridStringId.ConditionalFormattingPropertyGridRowBackColor: return "RowBackColor";
                case RadGridStringId.ConditionalFormattingPropertyGridRowForeColor: return "RowForeColor";
                case RadGridStringId.ConditionalFormattingPropertyGridRowTextAlignment: return "RowTextAlignment";
                case RadGridStringId.ConditionalFormattingPropertyGridTextAlignment: return "TextAlignment";
                case RadGridStringId.ConditionalFormattingPropertyGridCaseSensitiveDescription: return "Определяет, будут ли предприниматься с учетом регистра сравнения при оценке значений строки.";
                case RadGridStringId.ConditionalFormattingPropertyGridCellBackColorDescription: return "Введите цвет фона, чтобы использовать для клетки.";
                case RadGridStringId.ConditionalFormattingPropertyGridCellForeColorDescription: return "Введите цвет переднего плана, чтобы использоваться для клетки.";
                case RadGridStringId.ConditionalFormattingPropertyGridEnabledDescription: return "Определяет, будет ли условно активизирован (могут быть оценены и применены).";
                case RadGridStringId.ConditionalFormattingPropertyGridRowBackColorDescription: return "Enter the background color to be used for the entire row.";
                case RadGridStringId.ConditionalFormattingPropertyGridRowForeColorDescription: return "Enter the foreground color to be used for the entire row.";
                case RadGridStringId.ConditionalFormattingPropertyGridRowTextAlignmentDescription: return "Enter the alignment to be used for the cell values, when ApplyToRow is true.";
                case RadGridStringId.ConditionalFormattingPropertyGridTextAlignmentDescription: return "Enter the alignment to be used for the cell values.";
                case RadGridStringId.ColumnChooserFormCaption: return "Column Chooser";
                case RadGridStringId.ColumnChooserFormMessage: return "Drag a column header from the\ngrid here to remove it from\nthe current view.";
                case RadGridStringId.GroupingPanelDefaultMessage: return "Drag a column here to group by this column.";
                case RadGridStringId.GroupingPanelHeader: return "Group by:";
                case RadGridStringId.PagingPanelPagesLabel: return "Page";
                case RadGridStringId.PagingPanelOfPagesLabel: return "of";
                case RadGridStringId.NoDataText: return "No data to display";
                case RadGridStringId.CompositeFilterFormErrorCaption: return "Filter Error";
                case RadGridStringId.CompositeFilterFormInvalidFilter: return "The composite filter descriptor is not valid.";
                case RadGridStringId.ExpressionMenuItem: return "Expression";
                case RadGridStringId.ExpressionFormTitle: return "Expression Builder";
                case RadGridStringId.ExpressionFormFunctions: return "Functions";
                case RadGridStringId.ExpressionFormFunctionsText: return "Text";
                case RadGridStringId.ExpressionFormFunctionsAggregate: return "Aggregate";
                case RadGridStringId.ExpressionFormFunctionsDateTime: return "Date-Time";
                case RadGridStringId.ExpressionFormFunctionsLogical: return "Logical";
                case RadGridStringId.ExpressionFormFunctionsMath: return "Math";
                case RadGridStringId.ExpressionFormFunctionsOther: return "Other";
                case RadGridStringId.ExpressionFormOperators: return "Operators";
                case RadGridStringId.ExpressionFormConstants: return "Constants";
                case RadGridStringId.ExpressionFormFields: return "Fields";
                case RadGridStringId.ExpressionFormDescription: return "Description";
                case RadGridStringId.ExpressionFormResultPreview: return "Result preview";
                case RadGridStringId.ExpressionFormTooltipPlus: return "Plus";
                case RadGridStringId.ExpressionFormTooltipMinus: return "Minus";
                case RadGridStringId.ExpressionFormTooltipMultiply: return "Multiply";
                case RadGridStringId.ExpressionFormTooltipDivide: return "Divide";
                case RadGridStringId.ExpressionFormTooltipModulo: return "Modulo";
                case RadGridStringId.ExpressionFormTooltipEqual: return "Equal";
                case RadGridStringId.ExpressionFormTooltipNotEqual: return "Not Equal";
                case RadGridStringId.ExpressionFormTooltipLess: return "Less";
                case RadGridStringId.ExpressionFormTooltipLessOrEqual: return "Less Or Equal";
                case RadGridStringId.ExpressionFormTooltipGreaterOrEqual: return "Greater Or Equal";
                case RadGridStringId.ExpressionFormTooltipGreater: return "Greater";
                case RadGridStringId.ExpressionFormTooltipAnd: return "Logical \"AND\"";
                case RadGridStringId.ExpressionFormTooltipOr: return "Logical \"OR\"";
                case RadGridStringId.ExpressionFormTooltipNot: return "Logical \"NOT\"";
                case RadGridStringId.ExpressionFormAndButton: return string.Empty; //if empty, default button image is used
                case RadGridStringId.ExpressionFormOrButton: return string.Empty; //if empty, default button image is used
                case RadGridStringId.ExpressionFormNotButton: return string.Empty; //if empty, default button image is used
                case RadGridStringId.ExpressionFormOKButton: return "OK";
                case RadGridStringId.ExpressionFormCancelButton: return "Cancel";
            }
            return string.Empty;
        }


    }
}
