//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТипыЦен
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТипыЦен()
        {
            this.ЗаказПокупателя = new HashSet<ЗаказПокупателя>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public Nullable<bool> ДляРабот { get; set; }
        public Nullable<bool> ДляАвтомобилей { get; set; }
        public Nullable<int> ВалютаЦены { get; set; }
        public Nullable<bool> ВВалютеУчета { get; set; }
        public Nullable<bool> Закупка { get; set; }
        public Nullable<bool> Продажа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказПокупателя> ЗаказПокупателя { get; set; }
    }
}
