//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТипыДвигателей
    {
        public int id { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> ОбъемДвигателя { get; set; }
        public Nullable<int> ID_Авто { get; set; }
        public Nullable<int> ID_Комплект { get; set; }
    
        public virtual ВариантыКомплектации ВариантыКомплектации { get; set; }
    }
}
