//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoEntities : DbContext
    {
        public AutoEntities()
            : base(nameOrConnectionString: "name=AutoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Валюты> Валюты { get; set; }
        public virtual DbSet<ВариантыКомплектации> ВариантыКомплектации { get; set; }
        public virtual DbSet<ДоговорыВзаиморасчетов> ДоговорыВзаиморасчетов { get; set; }
        public virtual DbSet<ЕдиницыИзмерения> ЕдиницыИзмерения { get; set; }
        public virtual DbSet<ЗаказПокупателяТаблЧасть> ЗаказПокупателяТаблЧасть { get; set; }
        public virtual DbSet<Контрагенты> Контрагенты { get; set; }
        public virtual DbSet<ТипЗаказа> ТипЗаказа { get; set; }
        public virtual DbSet<ТипКПП> ТипКПП { get; set; }
        public virtual DbSet<ТипКузова> ТипКузова { get; set; }
        public virtual DbSet<ТипСалона> ТипСалона { get; set; }
        public virtual DbSet<ТипыДвигателей> ТипыДвигателей { get; set; }
        public virtual DbSet<ТипыЦен> ТипыЦен { get; set; }
        public virtual DbSet<Цвет> Цвет { get; set; }
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<ЗаказПокупателя> ЗаказПокупателя { get; set; }
        public virtual DbSet<ЗаказВид> ЗаказВид { get; set; }
    }
}
