//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобили()
        {
            this.ВариантыКомплектации = new HashSet<ВариантыКомплектации>();
            this.ТипСалона = new HashSet<ТипСалона>();
            this.Цвет1 = new HashSet<Цвет>();
            this.ЗаказПокупателя = new HashSet<ЗаказПокупателя>();
        }
    
        public int id { get; set; }
        public string VIN { get; set; }
        public string Наименование { get; set; }
        public string НаименованиеПолное { get; set; }
        public Nullable<System.DateTime> ГодВыпуска { get; set; }
        public string Комментарий { get; set; }
        public string НомерДвигателя { get; set; }
        public string НомерКузова { get; set; }
        public string НомерШасси { get; set; }
        public Nullable<int> Цвет { get; set; }
        public string ЦветКод { get; set; }
        public string НомерГаражный { get; set; }
        public Nullable<int> Поставщик { get; set; }
        public Nullable<int> Продавец { get; set; }
        public Nullable<System.DateTime> ДатаНачалаГарантии { get; set; }
        public Nullable<int> ВалютаУчета { get; set; }
        public Nullable<System.DateTime> ДатаОкончанияГарантии { get; set; }
        public string ОригинальныйVIN { get; set; }
        public Nullable<System.DateTime> ДатаРегистрации { get; set; }
    
        public virtual Валюты Валюты { get; set; }
        public virtual Контрагенты Контрагенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВариантыКомплектации> ВариантыКомплектации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТипСалона> ТипСалона { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Цвет> Цвет1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказПокупателя> ЗаказПокупателя { get; set; }
    }
}
