//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ВариантыКомплектации
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ВариантыКомплектации()
        {
            this.ТипКПП = new HashSet<ТипКПП>();
            this.ТипКузова = new HashSet<ТипКузова>();
            this.ТипыДвигателей = new HashSet<ТипыДвигателей>();
        }
    
        public int id { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string НаименованиеПолное { get; set; }
        public Nullable<int> ВалютаУчета { get; set; }
        public Nullable<int> МежсервисныйИнтервалТО { get; set; }
        public Nullable<int> МежсервисныйПробегТО { get; set; }
        public Nullable<int> ID_Авто { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТипКПП> ТипКПП { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТипКузова> ТипКузова { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТипыДвигателей> ТипыДвигателей { get; set; }
        public virtual Автомобили Автомобили { get; set; }
    }
}
