//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДоговорыВзаиморасчетов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ДоговорыВзаиморасчетов()
        {
            this.ЗаказПокупателя = new HashSet<ЗаказПокупателя>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public string ВидДоговора { get; set; }
        public Nullable<System.DateTime> ДатаНачала { get; set; }
        public Nullable<int> ВалютаВзаиморасчетов { get; set; }
        public string НомерДоговора { get; set; }
        public Nullable<System.DateTime> ДатаКонца { get; set; }
        public Nullable<int> ТипЦенПокупки { get; set; }
        public Nullable<int> ТипЦенПродажи { get; set; }
        public Nullable<int> ТипЦенРабот { get; set; }
        public string ВидОплаты { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказПокупателя> ЗаказПокупателя { get; set; }
    }
}
