//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказПокупателя
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗаказПокупателя()
        {
            this.ЗаказПокупателяТаблЧасть = new HashSet<ЗаказПокупателяТаблЧасть>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public string Автор { get; set; }
        public Nullable<int> Контрагент { get; set; }
        public Nullable<int> Организация { get; set; }
        public Nullable<int> ДоговорВзаиморасчетов { get; set; }
        public Nullable<int> Автомобиль { get; set; }
        public Nullable<int> ВалютаДокумента { get; set; }
        public Nullable<double> Курс { get; set; }
        public Nullable<int> ТипЦен { get; set; }
        public Nullable<double> СуммаДокумента { get; set; }
        public Nullable<double> ПроцентПредоплаты { get; set; }
        public Nullable<double> СуммаПредоплаты { get; set; }
        public Nullable<System.DateTime> СрокПоставки { get; set; }
        public string ВидОплаты { get; set; }
        public string Менеджер { get; set; }
        public Nullable<System.DateTime> ДатаСоздания { get; set; }
        public Nullable<int> ТипЗаказа { get; set; }
        public Nullable<System.DateTime> СрокСнятияРезерва { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Валюты Валюты { get; set; }
        public virtual ДоговорыВзаиморасчетов ДоговорыВзаиморасчетов { get; set; }
        public virtual Контрагенты Контрагенты { get; set; }
        public virtual ТипЗаказа ТипЗаказа1 { get; set; }
        public virtual ТипыЦен ТипыЦен { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказПокупателяТаблЧасть> ЗаказПокупателяТаблЧасть { get; set; }
    }
}
