//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaikovBSUIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказВид
    {
        public int Номер { get; set; }
        public string Наименование { get; set; }
        public string Автор { get; set; }
        public string Контрагент { get; set; }
        public string Организация { get; set; }
        public string Договор { get; set; }
        public string Автомобиль { get; set; }
        public Nullable<double> СуммаДокумента { get; set; }
        public string ТипЦены { get; set; }
        public string ТипЗаказа { get; set; }
        public string Валюта { get; set; }
        public Nullable<System.DateTime> СрокПоставки { get; set; }
        public Nullable<System.DateTime> СрокСнятияРезерва { get; set; }
        public Nullable<System.DateTime> ДатаСоздания { get; set; }
        public string Менеджер { get; set; }
    }
}
